title: ML for gas-surface dynamics
description: Documentation for ML-based gas-surface dynamics.
theme: just-the-docs

url: https://wgst.github.io/ml-gas-surface

# aux_links:
#   Template Repository: https://github.com/just-the-docs/just-the-docs-template
